name: Aggregate and Plot Steffim Stats

on:
  schedule:
    - cron: "5 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      run: |
        python3 -m pip install -r requirements.txt

    - name: Download and aggregate steffim stats
      run: |
        python3 main.py aggregate

    - name: Commit json to the repo
      run: |
        git config --global user.name "schicho/steffim"
        git config --global user.email "steffim[bot]@schicho.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Add historic data for the month' || true
        git push

  plot:
    needs: aggregate
    uses: ./.github/workflows/plot.yml
