name: Generate Steffim Stats

on:
  schedule:
    - cron: "5 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_plots:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      run: |
        python3 -m pip install -r requirements.txt

    - name: Generate SVGs
      run: |
        python3 main.py

    - name: Commit to the repo
      run: |
        git config --global user.name "schicho/steffim"
        git config --global user.email "steffim[bot]@schicho.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push
