name: Generate Steffim Plots

on: [workflow_dispatch, workflow_call]

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      run: |
        python3 -m pip install -r requirements.txt

    - name: Generate steffim plots
      run: |
        python3 main.py plot

    - name: Commit svgs to the repo
      run: |
        git config --global user.name "schicho/steffim"
        git config --global user.email "steffim[bot]@schicho.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update plots' || true
        git push
